version: '3'

services:

  crossbuild:
    build:
      context: .
      dockerfile: Dockerfile.crossbuild.distcc
    image: multiarch/crossbuild:distcc
    container_name: build_container
    volumes:
      - ${DOCKER_CROSS_PATH}:/workdir
      - ${DOCKER_CROSS_ENTRY_PATH}:/entrypoint
    environment:
      - DISTCC_ALLOWED_HOST=172.18.0.0/24 # NOTE: Update according to docker IP range.
      - CROSS_TRIPLE=arm-linux-gnueabihf
    entrypoint: /entrypoint/crossbuild_entrypoint.sh
