FROM multiarch/debian-debootstrap:arm64-stretch

MAINTAINER Miguel Arroyo (miguel@arroyo.me)

RUN apt-get update && apt-get -qq install \
    build-essential \
    distcc \
    ccache

# Install any necesary dependencies here.

RUN apt-get clean && \
    rm -rf /var/lib/apt